version: "3.8"

services:
  web:
    build:
      context: .
    container_name: web
    command: bundle exec rails server -b 0.0.0.0
    expose:
      - "3000"
    volumes:
      - ./public:/app/public
    environment:
      DATABASE_HOST: tech-books-circle-db.ckt8cykoag62.us-east-1.rds.amazonaws.com
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf